### ISSUE TITLE
`webhook.tk`  file is a mess that needs to die

### ISSUE THREAD

**Issue by ghost** [DecoraterBot-devs/DecoraterBot#8]
Honestly, what the fuck? You posted sensitive data to github, in a txt file. The webhook url is sensitive, and if a malicious person saw it, they could abuse it, as has happened yesterday. You also tried to copyright the url (!!!), which is basically the property of Discord, per se. Writing `Devs Only use.` wont persuade someone with malicious intent to listen to that, they would just ignore it. You devs need to look up what a webhook is, actually, I'll do it for you:
 - https://en.wikipedia.org/wiki/Webhook
 - https://discordapp.com/developers/docs/resources/webhook

Adding a `(c)` (no they literally added those 3 chars) doens't copyright anything, lmfao, they are three meaningless chars. Next, one dev said this:
```

Neonistic
-
Today at 10:32 AM
They were copyrighted and everything (webhook.tk) i made for US only, no one else shoud've got access to it, i contacted the devs and they said the webhooks links were only attached to me and ^ so we only should've had access to it, no one else. I will contact them again and see if it is correct, if not ill disable the webhook users and only make it so we can use them, ill (c) them again and make them with that function. Thank you```
TIme to rant about this, **ANYBODY CAN USE A WEBHOOK**, all you need to use a webhook is the url, which you blatantly posted to GitHub. Next, if you own a webhook, it doesn't mean others cant use it, the url is the only verification needed. You cant change that mechanism, and you cant restrict the use of a webhook url, except from hiding it from the public (*cough cough*). I'm crying with laughter at this guy's understanding of how webhooks, copyrights, and overall security works. This issue should be a reminder to me that I should never trust these devs with my sensitive info :/

**Comment by AraHaan** [comment]
true

**Comment by AraHaan** [comment]
Seems to be an issue with the website http://webhook.tk/ not encrypting inputs. The problem is I do not know how to contact the devs of that site to tell them they must encrypt the crap so that way stuff like this would not happen again. (As webhook urls for anything are sensitive information and must be encrypted or private.

**Comment by ghost** [comment]
You can easily encrypt this yourself, AES-256 and a hash should work fine

**Comment by ghost** [comment]
There is also the option of keeping the url private and non exposed

**Comment by AraHaan** [comment]
know what I see no point in webhook.tk at this time. Until the actual website itself asks for it to be encrypted / not exposed easily.

![](http://puu.sh/uYwKs/4f797ca97b.png)

**Comment by AraHaan** [comment]
done in https://github.com/AraHaan/DecoraterBot/commit/c5599fcf2bb6845f9fd8337df8ed24d7368c9dbc.
